apiVersion: apps/v1
kind: Deployment
metadata: 
  name: docker-k8s-demo-deployment
  labels:
    app: docker-k8s-demo1
spec: 
  replicas: 1
  selector: 
    matchLabels:
      app: docker-k8s-demo1
  template: 
    metadata:
      labels:
        app: docker-k8s-demo1
    spec:
      containers:
      - name: docker-k8s-demo1
        image: niteshnw/docker-demo1
        ports: 
        - containerPort: 8080